### ISSUE TITLE
One to many alias

### ISSUE THREAD

**Issue by haramjo** [qdrant/qdrant#1320]
**Is your feature request related to a problem? Please describe.**

Hi, I would like to keep every collection sized decently. So, I am considering to create a new collection when the previous one reached to a certain limit. But the problem is that I need to iteratively search through all split collections and aggregate the results on the client side while I don't want the useless traffic consuming the bandwidth.

**Describe the solution you'd like**

Some way how I can perform a search through multiple collections. ig) allowing one to many alias, or wildcards in collection name fields.

**Comment by azayarni** [comment]
We want better understand your use case. Let us discuss it on our Discord https://qdrant.to/discord

**Comment by vrdn-23** [comment]
@azayarni Our team is interested in an implementation similar to this. Is there any particular reason why this feature was not chosen to be implemented?

To cite a few sample use-cases, having a single mapping of an alias to multiple collections can streamline search requests across different collections in a better manner.

One example would be having something like `complete-logs` which can be an alias for multiple collections with `logs-${date}` and so on. Instead of having to search through all of them individually, it would be useful to have an API that allows us to traverse multiple collections as if they were a single collection. A similar functionality to what [OpenSearch aliases](https://opensearch.org/docs/latest/api-reference/index-apis/alias/) offers would be what seems ideal from a functional viewpoint.

**Comment by generall** [comment]
unlike text search request, where queries are universal, vector embeddings are not inter-compatible. In order to do multi-collection search we would have to enforce the same schema somehow, which we can't do.

But instead of multiple collections you can use custom (named) shards, which would give you essentially the same functionality

**Comment by timvisee** [comment]
If you think that isn't a responsibility of Qdrant: how about picking a random collection name in your on code when sending a request to Qdrant? I think it'd allow the same without changes.

**Comment by vrdn-23** [comment]
@timvisee I'm not sure I follow your comment.
Just to be clear, my argument for this use-case isn't with actually setting a different name for an existing collection. I am interested in a convenient way to search across distinct multiple collections with the same query, without having to run multiple separate requests. A many-to-one alias would be a means to that end is all I was suggesting.

**Comment by timvisee** [comment]
I thought this was about picking 'one of many' collections for each search, sorry for the misunderstanding.

Have you considered multi-tenancy within a single collection? That's what we usually recommend, partially because it scales much better. It allows searching over everything or just a subset. Or do you think that doesn't meet your requirements?

Documentation: https://qdrant.tech/documentation/guides/multiple-partitions/
