### ISSUE TITLE
Investigate GOAWAY/ENHANCE_YOUR_CALM error in internal gRPC under the high load

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#1907]
Qdrant in cluster deployment sometime refuses to answer search requests with `GoAway/ENHANCE_YOUR_CALM/Some resource has been exhausted` error.

## Current Behavior

500 error on the search request

## Steps to Reproduce

1. Run 3 nodes qdrant cluster (tested on the smallest machines in the Cloud)
2. Create collection with 3 shards. E.g. with the following command:

```
docker run --rm -it -e QDRANT_API_KEY="xxxx" --network=host qdrant/bfb ./bfb --uri 'https://xxxxxxxxxxx.eu-central-1-0.aws.cloud.qdrant.io:6334' -b 100 -p 10 -n 100000 --indexing-threshold 1000000
```

4. Run search load:

```
docker run --rm -it -e QDRANT_API_KEY="xxxxx" --network=host qdrant/bfb ./bfb --uri 'https://xxxxxxxxx.eu-central-1-0.aws.cloud.qdrant.io:6334' -b 100 -p 300 -n 100000 --indexing-threshold 1000000 --skip-create --skip-upload --skip-wait-index --search --search-limit 1000
```

6. After about ~2-4 mins see this error:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: status: Internal, message: "Service internal error: Failed to complete read operation: too many replicas returned an error", details: [], metadata: MetadataMap { headers: {"server": "awselb/2.0", "date": "Tue, 16 May 2023 18:53:50 GMT", "content-type": "application/grpc", "content-length": "0"} }', src/main.rs:341:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Internal logs are:

```
2023-05-16 20:47:04 | a388404f-babf-4df3-9ea8-1c1715d12fff | {"log":"[2023-05-16T18:47:04.354Z DEBUG hyper::proto::h2::client] client response error: stream closed because of a broken pipe\n","stream":"stderr","time":"2023-05-16T18:47:04.364193665Z"}
-- | -- | --
  |   | 2023-05-16 20:47:04 | a388404f-babf-4df3-9ea8-1c1715d12fff | {"log":"[2023-05-16T18:47:04.354Z DEBUG hyper::client::connect::dns] resolving host=\"qdrant-19638887-3b3a-46a8-ac10-52a4934b1378-0.qdrant-headless-19638887-3b3a-46a8-ac10-52a4934b1378\"\n","stream":"stderr","time":"2023-05-16T18:47:04.364167007Z"}
  |   | 2023-05-16 20:47:04 | a388404f-babf-4df3-9ea8-1c1715d12fff | {"log":"[2023-05-16T18:47:04.353Z DEBUG collection::shards::replica_set] Read operation failed: Service internal error: Tonic status error: Unknown error\n","stream":"stderr","time":"2023-05-16T18:47:04.353708704Z"}
  |   | 2023-05-16 20:47:04 | a388404f-babf-4df3-9ea8-1c1715d12fff | {"log":"[2023-05-16T18:47:04.352Z DEBUG hyper::proto::h2::client] client response error: stream closed because of a broken pipe\n","stream":"stderr","time":"2023-05-16T18:47:04.353697381Z"}
  |   | 2023-05-16 20:47:04 | a388404f-babf-4df3-9ea8-1c1715d12fff | {"log":"[2023-05-16T18:47:04.351Z DEBUG collection::shards::replica_set] Read operation failed: Service internal error: Tonic status error: Unknown error\n","stream":"stderr","time":"2023-05-16T18:47:04.351992361Z"}
  |   | 2023-05-16 20:47:04 | a388404f-babf-4df3-9ea8-1c1715d12fff | {"log":"[2023-05-16T18:47:04.351Z DEBUG hyper::proto::h2::client] client response error: stream closed because of a broken pipe\n","stream":"stderr","time":"2023-05-16T18:47:04.351481875Z"}
  |   | 2023-05-16 20:47:04 | a388404f-babf-4df3-9ea8-1c1715d12fff | {"log":"[2023-05-16T18:47:04.349Z DEBUG collection::shards::replica_set] Read operation failed: Service internal error: Tonic status error: Some resource has been exhausted\n","stream":"stderr","time":"2023-05-16T18:47:04.351473941Z"}
  |   | 2023-05-16 20:47:04 | a388404f-babf-4df3-9ea8-1c1715d12fff | {"log":"[2023-05-16T18:47:04.349Z DEBUG hyper::proto::h2::client] client response error: connection error received: detected excessive load generating behavior\n","stream":"stderr","time":"2023-05-16T18:47:04.34954914Z"}
  |   | 2023-05-16 20:47:04 | a388404f-babf-4df3-9ea8-1c1715d12fff | {"log":"[2023-05-16T18:47:04.349Z DEBUG hyper::client::service] connection error: hyper::Error(Http2, Error { kind: GoAway(b\"\", ENHANCE_YOUR_CALM, Remote) })\n","stream":"stderr","time":"2023-05-16T18:47:04.349535085Z"}

```

## Expected Behavior

no 500 errors

## Possible Solution

There might be some bad default config in tonic.

**Comment by agourlay** [comment]
I can see two leads for exploring the issue.

1. client keep alive is greater than server keep alive which creates stale connections
2. `detected excessive load generating behavior` could be related to excessive keep alive pinging (https://github.com/linkerd/linkerd2/issues/5988)

**Comment by timvisee** [comment]
Some of my additions I came across while glancing this:

We use [`keep_alive_while_idle`](https://docs.rs/tonic/latest/tonic/transport/channel/struct.Endpoint.html#method.keep_alive_while_idle) in our internal gRPC client. I wonder if we need to pair this with [`http2_keepalive_interval`](https://docs.rs/tonic/latest/tonic/transport/server/struct.Server.html#method.http2_keepalive_interval) in our server. I haven't reproduced this myself yet, so I haven't been able to test this.

It seems people mitigate this specific error with the `grpc.http2.max_ping_strikes` property, but we don't have access to that in tonic.

**Comment by ffuugoo** [comment]
> We use [keep_alive_while_idle](https://docs.rs/tonic/latest/tonic/transport/channel/struct.Endpoint.html#method.keep_alive_while_idle) in our internal gRPC client. I wonder if we need to pair this with [http2_keepalive_interval](https://docs.rs/tonic/latest/tonic/transport/server/struct.Server.html#method.http2_keepalive_interval) in our server.

As far as I can tell, `keep_alive_while_idle` is useless without `http2_keepalive_interval`. I've discovered it a while ago and kinda forgot to mention it. IIRC, if you look at `tonic`'s source code, `keep_alive_while_idle` eventually calls `hyper`'s `http2_keep_alive_while_idle`, and `http2_keep_alive_while_idle` docs says:

```
Sets whether HTTP2 keep-alive should apply while the connection is idle.

If disabled, keep-alive pings are only sent while there are open request/responses streams. If enabled, pings are also sent when no streams are active. Does nothing if http2_keep_alive_interval is disabled.

Default is false.
```

So it seems like it changes behavior of HTTP2 keep-alive slightly, but it does not mean that "connection would be dropped eventually without this option" or something like this. Both the name and documentation of this method is confusing, I guess, `tonic` fudged it up a bit, but then it was an API change to rename it.

**Comment by ffuugoo** [comment]
> I can see two leads for exploring the issue.
> 
>     1. client keep alive is greater than server keep alive which creates stale connections
> 
>     2. `detected excessive load generating behavior` could be related to excessive keep alive pinging ([Linkerd proxy gRPC connections to unmeshed services result in `TOO MANY PINGs` with specific keepalive settings linkerd/linkerd2#5988](https://github.com/linkerd/linkerd2/issues/5988))

I'll mention this once again, but AFAIK, we don't use gRPC/HTTP2 keep-alives *at all*. :/

**Comment by timvisee** [comment]
> I'll mention this once again, but AFAIK, we don't use gRPC/HTTP2 keep-alives _at all_. :/

Though we might not use it, we do have this though:

https://github.com/qdrant/qdrant/blob/be99de3e275eed9d249b94dcfd46f5ab51dd37b4/lib/api/src/grpc/dynamic_channel_pool.rs#L17

**Comment by ffuugoo** [comment]
> > I'll mention this once again, but AFAIK, we don't use gRPC/HTTP2 keep-alives _at all_. :/
> 
> Though we might not use it, we do have this though:
> 
> https://github.com/qdrant/qdrant/blob/be99de3e275eed9d249b94dcfd46f5ab51dd37b4/lib/api/src/grpc/dynamic_channel_pool.rs#L17

Not enough to enable keep-alive. I've updated my previous comments with more details.

**Comment by timvisee** [comment]
I've submitted a PR in `tonic` to provide an additional property we require to properly fix this: https://github.com/hyperium/tonic/pull/1401

**Comment by timvisee** [comment]
I figured it'd be good to document my findings and state how we move forward on this.

## The problem

The basic problem can be described like this:

- HTTP2 connections are used for internal gRPC connectivity
- When HTTP2 streams are dropped, they are reset
- As per HTTP2 [spec](https://httpwg.org/specs/rfc7540.html#StreamErrorHandler), a reset stream is kept for a while, [30 seconds in our case](https://docs.rs/h2/latest/h2/server/struct.Builder.html#method.reset_stream_duration)
- The reset stream is kept so it can ignore follow-up messages and doesn't error
- There's a hard limit of reset-but-kept streams, [20 in our case](https://docs.rs/hyper/latest/hyper/server/conn/struct.Http.html#method.http2_max_pending_accept_reset_streams)
- If the limit is reached, a GOAWAY/ENHANCE_YOUR_CALM error is returned to tell clients to back off
- So if we reset more than 20 streams concurrently within this 30 second time frame, the error shows up

It normally is a good idea for this limit to be here. If it wasn't, it would be very easy to initiate a denial of service attack if you'd open-and-reset a million streams. That is because a stream that is reset still uses resources while it is kept.

The GOAWAY errors happen internally, within cluster communication. If a user requests a search at a node, and cluster communication fails internally, the replica error is returned: "Service internal error: Failed to complete read operation: too many replicas returned an error"

It is relatively easy for clients to cause these connection drops. If they send a **lot** of long-running parallel requests with a short timeout on their client, a lot of client requests get dropped. These drops cascade into the internal gRPC pool causing a variety of issues.

During testing I triggered this problem in a different way than the issue description. The underlying problem seems to be the same though.

--

To summarize: because a lot of connections get dropped, our gRPC over HTTP2 connections break.

That is because of two problems:
- reset limit is very easy to reach
- consensus and operations use the same gRPC connections and pool

## Possible solutions

1. Increase limits, so we don't reach them
2. Use separate connection pool for consensus and operations
3. Make connection pool aware of reset streams, don't offer connections with high current reset count
4. Don't drop streams

It looks like implementing point 3 is very difficult at this time. It would require extensive error propagation.

Implementing point 4 is impossible.

We'll therefore go with implementing point 1, and possibly point 2 afterwards.

## Steps to fix

1. Increase reset limit

To resolve this we can greatly increase the reset limit. A huge number of reset streams is fine for us with regards to resource consumption.

We can't access this property right now however, for that we've opened this PR: https://github.com/hyperium/tonic/pull/1401

We're waiting on it to be merged. If that doesn't happen by this week, we'll fork next week until it gets merged upstream.

2. Decrease 30 second reset stream duration

Additionally we can decrease the 30 second duration for keeping reset streams.

We don't have access to this property either. This requires changes in both [hyper] and [tonic] to propagate the property.

3. Separate consensus/operation connection pool

In the future we can look into creating two separate pools, for consensus and operations. That way user operations do not interfere with cluster consensus.

4. Keep testing for this problem, possibly in CI

## Code

https://github.com/qdrant/qdrant/pull/1928

[hyper]: https://docs.rs/hyper
[tonic]: https://docs.rs/tonic

**Comment by generall** [comment]
https://github.com/qdrant/qdrant/releases/tag/v1.3.0

ToDo: create issue for the switching back to tonic upstream
