### ISSUE TITLE
Grouping API with_lookup should filter on the lookup collection not the grouped collection

### ISSUE THREAD

**Issue by keotic** [qdrant/qdrant#2321]
## Current Behavior
In the examples of Grouping API with lookup, there is a collection being grouped and a collection with the payloads being "looked at", current API's enable and apply filters on the grouped collection and not the "lookup" collection. As stated in the docs, the payloads should be on the "lookup" collections and not the grouped collections, hence there is no way to apply groups with lookup + filtering at the moment

## Possible Solution
Move the filters to the "with_lookup" payload, and apply them on the lookup collection

**Comment by keotic** [comment]
Any updates on this issue?
Its not clear how to use a lookup collection as a "single source of truth" if it can't be filtered.

**Comment by generall** [comment]
Hi @keotic, there is no simple way to implement the feature you mentioned, so currently it is known limitation.

In order to perform filter by `lookup` collection, we would need to implement a distributed join, a very costly operation in distributed systems. So for now, I am going to mark this feature request as `not planned`.

The workaround for behavior you are looking for is to duplicate only the minimal information into the `groupped` collection, and keep only those fields which are necessary for filtering, while keeping the heavy part of the payload in the `lookup` collection.

Please feel free to re-open this issue if you have any additional context we should consider.
