### ISSUE TITLE
Add info to collections API - HNSW + Payload indexes RAM consumption

### ISSUE THREAD

**Issue by keotic** [qdrant/qdrant#2364]
**Is your feature request related to a problem? Please describe.**
Currently the collections API only returns the points counts ( vectors + payload_schema).
It will be helpful to know the RAM consumption of the payload and vectors indexes in order to
tune Qdrant resources and debug large RAM consumptions we encounter even on medium collections with many indexes on the payload

**Describe the solution you'd like**
Add RAM usage along with points counts:

```


payload_schema": {
     "my_field_name": {
     "data_type": "keyword",
     "points": 109891,
      "RAM": 30GB
    },
}
```

**Comment by timvisee** [comment]
Measuring or tracking actual memory usage for this is an extremely hard problem. It may even be impossible to measure accurately. There are many reasons for this, but I won't go in further detail here. I think it would be a lot better to put our efforts elsewhere.

Now, I don't know whether we'd ever end up with something like this. But what about exposing the size of the index on disk. Memory consumption may be similar, in which case it could give a comparable indication.

**Comment by keotic** [comment]
Is it a hard problem for the payload indexes only?

**Comment by timvisee** [comment]
> Is it a hard problem for the payload indexes only?

Hard for everything. That is because memory allocation is not tracked in a way that we could calculate the usage for a subsystem.

The best pointers you can use right now is actual memory usage (resident set) of the full Qdrant process.

If you really want to know about the size in memory of a collection, you could copy that collection to a new Qdrant instance, start it with just that collection and measure.

Note that when using memory mapped data (data on disk) memory usage might wildly differ over time because the kernel would dynamically load/unload bits of data into memory based on system wide resource usage.

**Comment by keotic** [comment]
Understood, thank you for your quick reply

**Comment by timvisee** [comment]
Closing this now since I don't think we'll (nor can) every implement this or something similar with some usefulness.

Feel free to open this again if you have further questions or ideas on this.
