### ISSUE TITLE
Unable to parse (a very common string) UUID

### ISSUE THREAD

**Issue by dtrckd** [qdrant/qdrant#2622]
## Current Behavior
When trying to upsert a vector to an empty collection, I get this error from qdrant : 

```
status = StatusCode.INVALID_ARGUMENT
details = "Unable to parse UUID: B07YSTB5HX"
debug_error_string = "UNKNOWN:Error received from peer  {grpc_message:"Unable to parse UUID: B07YSTB5HX", grpc_status:3, created_time:"2023-09-10T04:53:55.856985037+02:00"}"
```

## Steps to Reproduce

```
from qdrant_client import QdrantClient, models

client = QdrantClient(url="http://localhost:6333", grpc_port=6334, prefer_grpc=True)
client.recreate_collection(
    collection_name="tryme",
    vectors_config=models.VectorParams(size=768, distance=models.Distance.COSINE),
)
vector = [0] * 768
client.upsert(
    collection_name="tryme",
    points=[
        models.PointStruct(
            id="b07ystb5hx",
            vector=vector,
        )
    ],
)
```

qdrant version : v1.5.0

## Expected Behavior

The vector should have been created with the given string id.

**Comment by generall** [comment]
Hi @dtrckd, this is expected behavior, please refer to the documentation: https://qdrant.tech/documentation/concepts/points/#point-ids

If you need to store exactly this ID along the vectors, you can use payload values instead.

Also, I noticed that your snippet contains zero-length vector: `vector = [0] * 768`.

Cosine distance is not defined for zero-length vectors, so your score will be NaN in this case.

**Comment by dtrckd** [comment]
Got it. Thank you.
