### ISSUE TITLE
Filter on vector presence

### ISSUE THREAD

**Issue by PieReissyet** [qdrant/qdrant#2737]
**Is your feature request related to a problem? Please describe.**
For some reasons I managed to introduce points with empty vectors in my collections. I could not reproduce the bug for it to be fixed but I would like to be able to find those points so I can re-upload or delete them.

**Describe the solution you'd like**
To be able to scroll the collection using a filter that would return vector with size 0 only

**Describe alternatives you've considered**
* Scrolling the whole collection with vector returned so I can see which ones have empty vectors but it takes a lof of time and memory with huge collections
* Scrolling the whole collection with no vector returned and catch exception while using the recommend route to get the ones with empty vectors but it's really time consuming too

**Additional context**
Here is the [discussion thread](https://discord.com/channels/907569970500743200/1149327864936808529) that lead to this request on Discord.

Thanks !

**Comment by DXist** [comment]
I guess that the filter should specify a list of named vectors to check for presence. If it's empty/not specified then a point is returned if any its vector is empty.

Should we handle the case when collection is configured with empty set of named vectors? In this case there is nothing to filter and all points are without vector data.

**Comment by generall** [comment]
> I guess that the filter should specify a list of named vectors to check for presence

I would start with just one vector per condition.

> Should we handle the case when collection is configured with empty set of named vectors?

Looks same as if non-existing vector name specified.

**Comment by DXist** [comment]
As I understand not present vector is stored as a dense unit or a sparse empty vector and is marked as deleted.

So for each segment we could use `deleted` bit vector (denote it to `Vdeleted`) to narrow the search of these empty vectors. It gives us internal ids of deleted vectors.

I see that each segment has `SimpleIdTracker` with `deleted` points BitVec (denote it to `Pdeleted`). We could use it to determine if a point with the given internal id is deleted. If it's not then this point has an empty vector.

**Comment by DXist** [comment]
Should we limit the scope of this issue to not deleted points?

**Comment by generall** [comment]
Deleted points can never be a result of filtered search, i think it is already accounted

**Comment by timvisee** [comment]
> Deleted points can never be a result of filtered search, i think it is already accounted

:man_facepalming: I'll update my above comment to prevent confusion.

**Comment by DXist** [comment]
I started with bitset intersection logic - https://github.com/qdrant/qdrant/pull/3394/files

I think about adding a new filter `Condition` and handle this filter in `Segment.read_filtered` which is called inside scroll logic.

It doesn't matter in which order points are returned by `read_filtered` because `Collection.scroll_by` will sort them by external id.

If the vector presence filter is the only provided filter then the order will be by internal id.

If we want to combine this filter with other filters then I see the following potential execution order:

1. filter by presence and construct a set of points
2. If the set is not empty and there are other filters (user provided filter is nested)
     * construct a new nested filter by replacing all presence filters by a single `HasId` filter with the previously constructed set.
     * apply other filters

I guess the author of the issue didn't plan to combine vector presence filter with other filters.

**Comment by DXist** [comment]
If there could be a lot of points with empty vectors then using scroll API and sorting results by external id will not be efficient.

It's possible to design a dedicated API call that paginates by internal id.

**Comment by DXist** [comment]
I've added very simple implementation that checks top-level condition and runs the implemented intersection logic - https://github.com/qdrant/qdrant/pull/3394/files#diff-f36a5225ec877c5136fb1f517f457503a33ed3a2c49af3434c2a0b11ab6efa4eR1090

@generall , I still not sure if the implementation should add a new filter and integrate with scroll API.

Meanwhile I noticed that the code actively uses trait objects in returned values.

For example this branch fails to build with compile errors like
```
172 |                         .map(|(_, segment)| segment.get().read().available_point_count())
    |                                             ^^^^^^^^^^^^^^^^^^^^ `SegmentEntry` cannot be made into an object
```

I think it's possible to have a macro with `match` and logic generic over `impl SegmentEntry` instead of segment.get() method to avoid dynamic dispatch. An example of code that works with two types of file descriptors and uses a macro - https://github.com/DXist/completeio/blob/main/src/driver/iour/op.rs#L20

**Comment by hp77-creator** [comment]
Hi @generall , is this closed with the latest merge?

**Comment by coszio** [comment]
We can close the issue now, but the condition will only be available from next minor release
