### ISSUE TITLE
Q: If I update the parameters of HNSW index (i.e., m/efConstruct), the index will be rebuilt or not?

### ISSUE THREAD

**Issue by liuxinbin12138** [qdrant/qdrant#2812]
By the way, is there a mechanism that I can unload a collection if I do not need at some instant?

**Comment by timvisee** [comment]
There currently is no API call to unload a collection from memory.

**Comment by MrBeeMovie** [comment]
> There currently is no API call to unload a collection from memory.
> 
> You could update the collection configuration to put the collection data on disk to reduce memory usage. But that isn't the same as unloading a collection.

Is unloading of collections a planned feature? I would find this useful.

**Comment by MrBeeMovie** [comment]
> > > There currently is no API call to unload a collection from memory.
> > > You could update the collection configuration to put the collection data on disk to reduce memory usage. But that isn't the same as unloading a collection.
> > 
> > 
> > Is unloading of collections a planned feature? I would find this useful.
> 
> Would you mind to elaborate on what might be a use case for this?

My team and I do a lot of testing that requires us to change the configuration of a collection and the schema for our points. Because of this we end of making a lot of different versions of the same collections that we use to compare to each other and test new features for our software. We don't want to necessarily just directly update the collection itself or delete old versions in case we want to rollback to a previous version quickly. We also don't want to necessarily use the snapshot API to handle keeping the old versions since it makes it difficult for us to see at a glance what versions have different schemas and we won't have a local copy in Qdrant to get up and ready for use quickly. Our collections have a version number in their name which makes it easy to differentiate between schemas and config. This could be possible by naming the snapshots but we will then have to mark them with a version and store in a different location then have to upload back to Qdrant when we need to use them. It is not necessarily impossible with the snapshot API but it would be easier for us to be able to store local copies of collections in Qdrant and have the snapshots as backups in case there is data loss. Sorry, for the long response. Thank you for your time!
