### ISSUE TITLE
Indexing VS Search

### ISSUE THREAD

**Issue by ava57r** [qdrant/qdrant#2822]
Hello
Could You explain please.
How Can I fins a balance between indexing and search?

I use cluster
I have 4 instances with huge upserts
When qdrant builds index search requests send
I get a message like this

```
Caused by:\n    0: status: Cancelled, message: \"Timeout expired\", details: [], metadata: MetadataMap { headers: {} }\n    1: transport error\n    2: Timeout expired.
```

**Comment by generall** [comment]
If you need to search and upsert at the same time, you might want to look at [indexed_only](https://qdrant.tech/documentation/concepts/search/?selector=aHRtbCA%2BIGJvZHkgPiBkaXY6bnRoLW9mLXR5cGUoMSkgPiBzZWN0aW9uID4gZGl2ID4gZGl2ID4gZGl2ID4gYXJ0aWNsZSA%2BIHVsOm50aC1vZi10eXBlKDMpID4gbGk6bnRoLW9mLXR5cGUoMyk%3D) param of the search requests, if eventual indexing is OK for your usecase.

Another possible solution is read/write segregation, but it might be a bit more tricky to setup.

**Comment by ava57r** [comment]
I read messages in my log like this either

```
WARN collection::collection_manager::holders::segment_holder: Trying to read-lock all collection segments is taking a long time. This could be a deadlock and may block new updates.
```

**Comment by ava57r** [comment]
I already use indexed_only param.

> Another possible solution is read/write segregation, but it might be a bit more tricky to setup.

It is interesting!

**Comment by ava57r** [comment]
Can I set timeout for search requests?
I set  timeout = 60 sec in qdrant rust client but I 'm not sure about it.

**Comment by timvisee** [comment]
> I read messages in my log like this either
> 
> ```
> WARN collection::collection_manager::holders::segment_holder: Trying to read-lock all collection segments is taking a long time. This could be a deadlock and may block new updates.
> ```

Thank you for pointing to this. Though this doesn't clearly describe the problem it does point to a specific place in code.

> Can I set timeout for search requests?
> I set timeout = 60 sec in qdrant rust client but I 'm not sure about it.

At this time setting the search timeout only affects the client. In other words, it specifies the time after which the client cuts the connection. The server currently has a fixed timeout.

Customizing the search timeout on the server is being worked on in <https://github.com/qdrant/qdrant/pull/2748>.

**Comment by ava57r** [comment]
> Another possible solution is read/write segregation, but it might be a bit more tricky to setup.

Could You explain, please?

**Comment by martyanov** [comment]
We use the following strategy, but it really depends on specific use cases and amount of data. For example, you need to ingest 5 million points per day, so monthly it is around 150 millions. If we put all the points into a single collection the reindexing  will be really slow and we somehow need to amortize reindexing cost, because it is increasing every `index_threshold`. What we do:

1. Create 5 collections per day, 1 million points per single collection
2. Adjust `index_threshold` for each collection, if its around `100k` then only 9 reindexing is required per collection
3. Perform parallel search across all the required collections
4. On the next day merge all the collections into a single collection and reindex it once
5. Repeat

In the scenario I assume that collections are sort-of immutable and append-only. It would be great is something similar is implemented out of the box.

**Comment by ava57r** [comment]
Thanks
