### ISSUE TITLE
Binaries for Linux ARM64

### ISSUE THREAD

**Issue by jbonet-df** [qdrant/qdrant#3056]
I would like to request binaries for the arm64 arch, as it is a popular architecture for cloud environments.

For me, building from source every time there is an update, makes it really tedious.

**Comment by timvisee** [comment]
We don't ship an `aarch64-unknown-linux-gnu` targeted raw binary at this time as part of our releases.

However, we do [provide](https://hub.docker.com/r/qdrant/qdrant/tags) Docker images for arm64 which should run perfectly fine on arm64 hardware. This is also our recommended way of [running](https://qdrant.tech/documentation/quick-start/#download-and-run) Qdrant.

Is using our Docker image an option, or is that undesirable in your case?

Related to <https://github.com/orgs/qdrant/discussions/3041>

**Comment by jbonet-df** [comment]
No we do not use docker, and I don't see why provide mac binaries for arm instead of linux, weird choice.

**Comment by timvisee** [comment]
> and I don't see why provide mac binaries for arm instead of linux, weird choice.

It is because macOS doesn't run Docker natively.

It's definitely something we can do. I'll discuss this with other team members.

**Comment by timvisee** [comment]
> I'll discuss this with other team members.

We all agreed that it'd be nice to release binaries for ARM64 as well.

But before we can do that, we should resolve <https://github.com/qdrant/qdrant/issues/2656>. Shipping GNU libc (rather than musl) binaries is problematic, as it would require the host to have the exact same set of system libraries. This is also a problem with the current x86_64 binaries. And due to that, it would in fact be better to compile from source yourself. I don't think we want to take the route of shipping AppImage blobs.

I'll leave this open so we can eventually do this. But again, we should likely resolve <https://github.com/qdrant/qdrant/issues/2656> first.

**Comment by timvisee** [comment]
Static ARM64 binaries are now released: https://github.com/qdrant/qdrant/releases/
