### ISSUE TITLE
qdrant Modifies operation permissions

### ISSUE THREAD

**Issue by zhangzf875** [qdrant/qdrant#3276]
How to set qdrant to read-only mode, so that data can only read and not insert and delete the change operation;
Then how to open the insert and delete change operations

**Comment by generall** [comment]
Hi @zhangzf875, as of now qdrant can't work with read-only file system, however, you can configure read-only access to the system: https://qdrant.tech/documentation/guides/security/#read-only-api-key

**Comment by locustbaby** [comment]
Like Read/Write Separation？

**Comment by timvisee** [comment]
> Like Read/Write Separation？

No. Read-only API keys don't provide read/write separation as you'd still read/write on the same nodes.

To get true read/write separation you'd have to configure and manage this yourself. Maybe you can configure your application to read/write on specific nodes. Otherwise you may be able to configure a reverse proxy to do the separation for you.
