### ISSUE TITLE
Try to allow `f16` vectors in storage

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#3333]
**Is your feature request related to a problem? Please describe.**

Currently qdrant uses hard-coded f32 as a data type for all vectors (except quantized).
But in many applications storing f32 might be too expensive and redundant. 

It would be interesting to try to eventually migrate to dynamic switch between f16 and f32 precisions.

**Describe the solution you'd like**

As a first step of the migration, we'd like to experiment with compile-time switch first.

To do this, we would need to introduce a feature-flag, that would switch from f32 to f16.

Make sure that all qdrant functions work properly with f16 type enabled, such as:

- quantization
- mmaps
- querying
- indexing
- ...

**Describe alternatives you've considered**

Make storage type generic, but this easily might be too much effort for a single PR, so it is better to postpone for another iteration.

**Additional context**

We would need to pay extra attention for query types, as interface (REST and gRPC) should not change once we switch to f16.

---

Note for contributors: Please consider this as tracking issue. If you think that it would be beneficial to split the task into multiple smaller PRs, please you are welcome to do so. Bounty will be rewarded for each PR independently

**Comment by xzfc** [comment]
Sent a PR #3373. Not sure if I am on the right track, so there are a few questions:

1. What kind of 16-bit floats do you want: `fp32` or `bf32`? The `half` crate has the both.

2. Which types exactly do we need to update? I've stumbled upon these candidates:
- `segment::data_types::vectors::VectorElementType` — for sure, we need to update this one. Am I right?
- `sparse::common::types::DimWeight` — I think we need to update this too.
- `common::common::types::ScoreType` — what about this?
I did not see any `f32` mentions in `lib/storage`, so, it's not the crate that we are supposed to update?

3. I've started by changing the `segment` crate (PR #3373). Is this the right place to fix? Do you have a suggestion on what should be changed next?

**Comment by PranayB003** [comment]
> sparse::common::types::DimWeight — I think we need to update this too.

I was thinking this needs to be changed as well. Hadn't figured out the rest so didn't implement anything yet. Overall it seems like there are lots of changes to be made (as evident from your PR), do you think it will be a good idea to split them among us?

**Comment by coszio** [comment]
I believe `ScoreType` should remain the same, this is issue refers to the vector representation only.

Also yes, sparse values (`sparse::common::types::DimWeight`) also count as vector elements, so updating them should be included. This probably would need a separate PR from the dense vectors, though.

**Comment by xhjkl** [comment]
I see there are attempts already, but I still would still like to try too, if no one minds.

/attempt #3333

**Comment by 0xSaksham** [comment]
I see this issue is still not resolved, I'll take a look

**Comment by maksimryndin** [comment]
@generall I took this issue - work in progress here https://github.com/qdrant/qdrant/pull/3922

**Comment by charles-r-earp** [comment]
/attempt #3333

Previous PR #4032.

Based on feedback, reduce the scope of the changes to just vector_storage, not change data_types::vectors::VectorElementType. 

All changes within segment crate.

f16 feature (adds half dependency).

Implement data_types::primitive::PrimitiveVectorElement for f16.

In vector_storage::vector_storage_base:
```
#[cfg(not(feature = "f16"))]
pub(crate) type VectorStorageElementType = VectorElementType;
#[cfg(feature = "f16")]
pub(crate) type VectorStorageElementType = half::f16;
```
This will be the type used in VectorStorageEnum:
```
pub enum VectorStorageEnum {
    DenseSimple(SimpleDenseVectorStorage<VectorStorageElementType>),
    DenseMemmap(Box<MemmapDenseVectorStorage<VectorStorageElementType>>),
    DenseAppendableMemmap(Box<AppendableMmapDenseVectorStorage<VectorStorageElementType>>),
    SparseSimple(SimpleSparseVectorStorage),
    MultiDenseSimple(SimpleMultiDenseVectorStorage),
}
```

Add new mod spaces::metric_f16 (feature f16). Implement spaces::Metric<f16> for all metrics.

For types::Distance, make vector functions generic:
```
impl Distance {
    pub fn preprocess_vector<T: PrimitiveVectorElement>(
            &self,
            vector: DenseVector,
        ) -> TypedDenseVector<T>
        where
            CosineMetric: Metric<T>,
            EuclidMetric: Metric<T>,
            DotProductMetric: Metric<T>,
            ManhattanMetric: Metric<T>;
    pub fn similarity<T: PrimitiveVectorElement>(&self, v1: &[T], v2: &[T]) -> ScoreType
        where
            CosineMetric: Metric<T>,
            EuclidMetric: Metric<T>,
            DotProductMetric: Metric<T>,
            ManhattanMetric: Metric<T>;
}
```
These are called with both VectorElementType and VectorStorageElementType. 

Implementers of vector_storage::query_scorer::QueryScorer and related functions would be generic over `TMetric: Metric<VectorStorageElementType>` (and VectorElementType as required). For example (vector_storage::raw_scorer):
```
fn new_multi_scorer_with_metric<
    'a,
    TMetric: Metric<VectorStorageElementType> + Metric<VectorElementType> + 'a,
    TVectorStorage: MultiVectorStorage,
>(
    query: QueryVector,
    vector_storage: &'a TVectorStorage,
    point_deleted: &'a BitSlice,
    is_stopped: &'a AtomicBool,
) -> OperationResult<Box<dyn RawScorer + 'a>>;
```
This is because the query is VectorElementType, while vector_storage is VectorStorageElementType.

**Comment by xhjkl** [comment]
I've rebased my changes after the generic storage landed in #3900.

I apologize for a half-baked pull-request, but I otherwise would feel guilty to comment on the issue without having submitted anything.

I'm very excited about f16, and I'd love to contribute this very feature to Qdrant to see what speedups it could bring.
However, I believe it may not be practical to proceed with this contribution right now, because there are following prerequisites not met:
* `quantization`, which lives in a separate repository, does not have the corresponding `f16` switch, and I don't see a linked issue in the description;
* even if we adapt `quantization` to handle `f16`, we are left with reimplementing distances with f16 SIMDs, and this is a real obstacle, see below;
* the holy grail of this issue, so far as i understood it, is to calculate the distance without having to cast between floats of different widths, but until the language supports `f16` natively, we are still left with some casts here and there, and this still worsens the developer experience.

## f16 SIMD
As mentioned above, the native support of f16 in the language would allow us to write `(-1..=+1)` without having to do the squats with num-traits along the lines of `let one = VectorElementType::ONE; (-one..=one)` and suchlike.

Even if the language supports natively f16 one day, we'll have to expand our SIMD implementations accordingly, and, at least for NEON, the f16-wide intrinsics are not passed through to the stdlib. That is, without resorting to hand-written assembly, you can have `vfmaq_f32`, but not `vfmaq_f16`.

There is even an issue for that, but that one is apparently stall:
https://github.com/rust-lang/stdarch/issues/344

## GPGPU
In theory, if we absolutely need f16 in Qdrant, I could do that through GPU, because almost all server-grade GPUs support fp16 now. But that would require a massive overhaul across the whole Qdrant, so this is far outside the scope of this issue.

----

All in all, I believe this issue is best postponed until one of the above happens. At the very least, I believe we should rip "good first issue" tag off it: it may be deceptively simple, but, in my experience, at the current state of affairs, it is not beginner-friendly at all, and it attracts contributors who end up in a dead end.

@generall, @IvanPleshkov, would love to chime in!

**Comment by generall** [comment]
Hey @xhjkl, @charles-r-earp, thanks for your contrinution!

It seems to me that I better close this issue and re-formulate it in more actual way. I believe current "desired" solution is misleading and after introduction of the generic storage we don't want to have compile time flag anymore.

**Comment by mqudsi** [comment]
Just pointing out that for a lot of usecases it is quite possible/likely that the "raw" embeddings or vectors are already at fp16 resolution (i.e. anytime you are running a model converted from fp32 to fp16 for speed or memory purposes) so storing them as fp32 is a wasteful doubling of storage/memory.

**Comment by generall** [comment]
@mqudsi FYI, qdrant does support fp16 out of the box now. https://qdrant.tech/documentation/concepts/vectors/#datatypes

**Comment by mqudsi** [comment]
Thanks @generall, the other pages of the docs left the impression the original vectors were hardcoded as fp32 (but I’m sure I was looking at ones that predated the updated datatype support).

Native fp16 is very handy!
