### ISSUE TITLE
400 from upsert. it says the json is invalid but it's from your swagger so uh???

### ISSUE THREAD

**Issue by unktomi** [qdrant/qdrant#3451]
Using the CURL command provided by the swagger page https://ui.qdrant.tech/#/points/upsert_points doesn't even work.
## Steps to Reproduce

'http://localhost:6333/collections/SummaryNode/points?wait=true' \
>   -H 'accept: application/json' \
>   -H 'Content-Type: application/json' \
>   -d '{
>   "batch": {
>     "ids": [
>       0,
>       "3fa85f64-5717-4562-b3fc-2c963f66afa6"
>     ],
>     "vectors": [
>       [
>         0, 1, 2, 3
>       ]
>     ],
>     "payloads": [
>       {
>         "additionalProp1": {}
>       },
>       "string"
>     ]
>   },
>   "shard_key": "string"
> }'
{"status":{"error":"Format error in JSON body: data did not match any variant of untagged enum PointInsertOperations"},"time":0.

This occurs with the latest main as well as tags/v1.7.3

## Expected Behavior
Should be obvious

## Context (Environment)

qdrant release build Compiled and run on macos 13.1 apple silicon

**Comment by generall** [comment]
Hi @unktomi, number of IDs should match number of vectors and payloads in your case. Also `"string"` is not a valid payload

**Comment by JoshuaCWebDeveloper** [comment]
What is a valid payload? The docs indicate that `"string"` should be valid: https://qdrant.github.io/qdrant/redoc/index.html#tag/points/operation/upsert_points

**Comment by JoshuaCWebDeveloper** [comment]
In my case, this was caused by using arbitrary string ids (https://github.com/qdrant/qdrant/issues/551).

I think this issue should be focused on two things:
- Improving this error message so that it tells us which specific properties are wrong and what specifically is wrong with them
- Updating all documentation to accurately reflect the state of the API (or visa versa)

**Comment by timvisee** [comment]
> Updating all documentation to accurately reflect the state of the API (or visa versa)

I believe it does show this. It shows `string<uuid>`, which is right, because you are allowed to use UUIDs in form of a string.

![image](https://github.com/qdrant/qdrant/assets/856222/dbb2a4f0-0862-43c9-b4b2-09408084d053)

**Comment by JoshuaCWebDeveloper** [comment]
@timvisee Yes, for the string id format, that is correct; however, the docs indicate in two separate places (linked to above) that `"string"` should be a valid payload. I haven't found anything suggesting what payloads are valid and not except for the above comment.

Also, the docs would be easier to parse if I didn't have to expand each property in order to get requirements like the id needing to be a uuid. The full type information of the id property would have ideally been visible here: 
![image](https://github.com/qdrant/qdrant/assets/6536826/d8c3ac43-4de3-41d3-9582-d02e356352bc)

**Comment by timvisee** [comment]
Taking another look at your original post, I think we're talking about the wrong thing here.

First of all, there's point IDs and payload, these two are different. Each point must have an ID, which can be an integer or UUID (string). As payload, you can provide any JSON object.

The important thing is that payloads must be a JSON object, not any JSON value. I see that you passed a `"string"` as payload in once case, which is not a JSON object.

Does your  request work if you change your payloads to be something like:


```json
"payloads": [
  { "additionalProp1": {} },
  { "additionalProp2": "string" }
  ]
}
```

**Comment by codenoid** [comment]
oh, this is really weird, I don't know

why shouldn't allow any kind of string? I might use nanoid, or anything, it should be on user to decide

so this is are only "valid string" 

```python
                PointStruct(
                    id=str(uuidpy.uuid4()),
                    vector=embedding,
                    payload={"org_id": request.state.org_id},
                )
```
