### ISSUE TITLE
Boost points depending on values in the payload

### ISSUE THREAD

**Issue by m1stegmann** [qdrant/qdrant#3457]
We have points of diverse types in the database (news, blog posts, articles, web pages, ...) and now want to find matching points, but "boost" the individual points depending on the type or age and thus influence the sorting.

We could imagine storing one or more of these boosts in the payload as a float and then multiplying the score of the point by these boosts and then sorting the search result according to this calculated score,

**Comment by generall** [comment]
Hey @m1stegmann, our current understanding is that combination of semantic score with manually-defined "boost" is an anti-pattern and we won't support or encourage it.

The reason is following:

- unlike boosting in bm25 and text search, vector representation are trained. So when you do boosts, thresholds or something like this, you basically say you know better than the model. But in majority of cases that's a illusion. 
- It is unstable. Small change in those boost params and you can get exponentially different number of results / shift in distribution.
- It is model sensitive. As soon as you would want to change the model to a newer version, your hand-made boosting params became outdated immediately.


What we propose to do instead is to use re-ranking:

- Either pre-fetch candidates with vector search and apply a learn-to-rank model, which will take into account scores with proper weight and others stored parameters
- Or retrieve data by ordered stored value and re-score it using vectors

Either way would be more flexible and robus than applying boosts

**Comment by ffletcherr** [comment]
@generall , The whole issue is not just about retrieval based on relevance; in many cases, business logic is involved. For example, we may want to slightly boost newer records, or we may want a specific category of products to be shown less frequently unless they are highly relevant and there are no better alternatives. There are numerous examples of business logic where the solution is to boost results based on fields in their payload.

**Comment by jqueguiner** [comment]
An alternative could be that after the retrieval you add a rerank booster. For instance for freshness of articles: Calculate the nb of days between today and the date of the article and ponderate the cosine similarity to penalize the similarity angle between the vectors and the query. To let’s say the oldest one will be penalized by 20% the newest by 0% 
Oldest is 120 days old it means that you penalize the decay the similarity by 1% for every block of 3 days of oldness.
Of you could boost the similarity (it's just the other way around).

**Comment by wellinxu** [comment]
Hi, @generall 
Boost is a very useful feature in search domain, just like what @ffletcherr  said. 

1. boost can be used with vector score like bm25 score. Perhaps there is an  illusion, but it doesn't matter. The changes can be very subtle.
2. The results are different from the results of original vector score, but they are same when both use boost.
3. Changing model is much more complicated than adjusting boost. So when changing model, adjusting boost is fine.
4. Rerank like corss-encoder model is heavy, and it can't handle some field like date or authority.
5. We can't use ltr model like gbdt or NN in qdrant. It can be used in solr or es.
6. Retrieving data by ordered stored value and then re-scoring with vector, the relevance is poor and too concentrated.

Please consider adding boost function again. Thanks.

**Comment by ferhimedamine** [comment]
I'll respectfully push back on the anti-pattern framing here. For agent memory use cases, the model genuinely does *not* know better -- embeddings capture semantic similarity but have zero awareness of temporal relevance or access frequency. When an agent recalls "the user prefers dark mode," it needs to know whether that was stated yesterday or 6 months ago (and possibly reversed since). No amount of reranking with a cross-encoder fixes this because the signal isn't in the text at all.

What @jqueguiner describes is close to what we ended up building. The key refinement we found: decay should be based on **last-access time**, not creation time. A memory that keeps getting recalled is demonstrably important regardless of age, while a memory created yesterday but never accessed again should fade faster than one created a year ago that gets hit weekly. This is a lightweight exponential decay at retrieval time, not a learn-to-rank pipeline -- the complexity tradeoff of LTR for this is massive overkill.

We implemented this as an access-weighted importance score in our [decay engine](https://github.com/dakera-ai/dakera-deploy/blob/main/docker-compose.yml) (Rust, sits between the HNSW index and the API layer). Every recall bumps the last-access timestamp and importance; the retrieval scorer then blends cosine similarity with the decay-adjusted importance. It's stable, model-agnostic, and adds ~0.2ms per query. The "model knows better" argument holds for pure semantic search but breaks down the moment your scoring function needs to account for signals the embedding was never trained on.
