### ISSUE TITLE
Cannot get jar with version 1.7.3 from maven repo

### ISSUE THREAD

**Issue by forestwanglin** [qdrant/qdrant#3470]
I noticed that v1.7.3 is released a month ago. But it is not deploy to maven, could anyone deploy it?

**Comment by timvisee** [comment]
The versions of the main Qdrant product and the Java client may diverge a bit.

Sometimes we need to do a small patch on the main product, but can leave our clients as is.

I therefore assume using the latest Java client should be totally fine with Qdrant 1.7.3.

Closing this now since I think this resolves it. Feel free to open it again if you have further issues.
