### ISSUE TITLE
`timed out` on /delete

### ISSUE THREAD

**Issue by KastanDay** [qdrant/qdrant#3654]
## Current Behavior

Is there any way to ensure my delete operations complete? 
Does the operation complete in the background and just the HTTP request hits timeout?

## Steps to Reproduce

Python client `qdrant-client==1.7.3`
Qdrant via Docker `v1.7.4`

Code to reproduce: Deleting points by a keyword filter. I expect only one point to be deleted.
```py
# Raises: timed out
self.qdrant_client.delete(
    collection_name=os.environ['QDRANT_COLLECTION_NAME'],
    points_selector=models.Filter(must=[
        models.FieldCondition(
            key="url",
            match=models.MatchValue(value=source_url),
        ),
    ]),
)
```
I do have an index on the `url` field. 

GET collections/my-collection
```
{
  "result": {
    "status": "green",
    "optimizer_status": "ok",
    "vectors_count": 870603,
    "indexed_vectors_count": 883096,
    "points_count": 869396,
    "segments_count": 7,
    "config": {
      "params": {
        "vectors": {
          "size": 1536,
          "distance": "Cosine"
        },
        "shard_number": 1,
        "replication_factor": 1,
        "write_consistency_factor": 1,
        "on_disk_payload": false
      },
      "hnsw_config": {
        "m": 16,
        "ef_construct": 100,
        "full_scan_threshold": 10000,
        "max_indexing_threads": 0,
        "on_disk": false
      },
      "optimizer_config": {
        "deleted_threshold": 0.2,
        "vacuum_min_vector_number": 1000,
        "default_segment_number": 0,
        "max_segment_size": null,
        "memmap_threshold": 20000,
        "indexing_threshold": 20000,
        "flush_interval_sec": 5,
        "max_optimization_threads": 1
      },
      "wal_config": {
        "wal_capacity_mb": 32,
        "wal_segments_ahead": 0
      },
      "quantization_config": {
        "scalar": {
          "type": "int8",
          "always_ram": true
        }
      }
    },
    "payload_schema": {
      "course_name": {
        "data_type": "keyword",
        "points": 869393
      },
      "url": {
        "data_type": "text",
        "points": 638197
      },
      "s3_path": {
        "data_type": "text",
        "points": 869393
      }
    }
  },
  "status": "ok",
  "time": 0.000074336
}
```

**Comment by generall** [comment]
hey @KastanDay, data type "text" for urls doesn't seem to be a right choice. More likely you want to use `keywords` instead of `text` there

**Comment by KastanDay** [comment]
Thanks @generall, one other Q: does the operation complete in the background and only the HTTP request hits a timeout? Probably not...

**Comment by generall** [comment]
> Thanks @generall, one other Q: does the operation complete in the background and only the HTTP request hits a timeout? Probably not...

Update operations will be completed in background

**Comment by KastanDay** [comment]
That works for me. I'll refactor my payloads to `keyword` thanks.

**Comment by StratosKakalis** [comment]
Hello @generall , I would like to add a question to this thread. If the deletion operations complete in the background then why does the qdrant_client.delete operation hang? Should we just run it with the default timeout and ignore it? I have a very large collection (80m vectors and growing) and I am concerned if these deletion operations are trully performed or cancelled, because I also use filters.

**Comment by timvisee** [comment]
> Hello [@generall](https://github.com/generall) , I would like to add a question to this thread. If the deletion operations complete in the background then why does the qdrant_client.delete operation hang? Should we just run it with the default timeout and ignore it? I have a very large collection (80m vectors and growing) and I am concerned if these deletion operations are trully performed or cancelled, because I also use filters.

Write operations (including deletes) are either accepted or not. Once accepted, they will be run to completion.

By default, an operation like this doesn't wait and responds as soon as the operation has been acknowledged. Then you're sure the operation will be eventually (likely immediately) executed.

If you set the `wait=true` flag, the client will actually wait for the operation to be fully applied. This is significant, because as soon as it responds you're sure the deleted data cannot be queried anymore. An operation like this is accompanied by a timeout so that your client doesn't hang forever. Even if it times out, you can still expect it to be executed.

Delete operations taking a long time can be a red flag pointing to bad usage. Please make sure that any filters you use in deletes have an appropriate [payload index](https://qdrant.tech/documentation/concepts/indexing/#payload-index) configured. Otherwise you may want to reduce the size of your delete operations and chunk.

Ps, please don't mention directly

**Comment by StratosKakalis** [comment]
Thank you for the quick response and sorry for the direct mention. 

Is the default value of wait=true? Because I didn't specify any value. If it's false then I assume something is wrong on my end. I do have a payload index configured for the one payload field I use for filtering (keyword type). And the deletion operation is fairly small (only 20 points).

As I said my collection is fairly large (80M vecotrs), could this delay still be normal due to the size of the collection or should I still expect near instant acknowledgment of the deletion request? 

In case this is simply a performance issue with filtering on a large collection then would directly using the vector ids for deletions help?
 
Thank you in advance

**Comment by timvisee** [comment]
It is indeed `wait=false` by default.

> I do have a payload index configured for the one payload field I use for filtering (keyword type). And the deletion operation is fairly small (only 20 points).

Sounds good!

> As I said my collection is fairly large (80M vecotrs), could this delay still be normal due to the size of the collection or should I still expect near instant acknowledgment of the deletion request?

I would expect instant acknowledgement. Or more specifically, definitely below 100ms.

> then would directly using the vector ids for deletions help?

Directly deleting point IDs will always be faster. But I don't think it'd resolve the long request time problem you're seeing now.

Is it possible that your cluster is very busy? Maybe because of large ingestion or due to heavy optimizations. Could it be hitting IO bottlenecks?

If you fetch your collection info with `GET /collections/my_collection`, does the payload index list more than zero points indexed?

**Comment by StratosKakalis** [comment]
Thank you for your help, 

Sorry if this is a rookie question but I was under the impression that I had successfully indexed two fields in my collection "pid" and "doi" but i realise that they may be wrong: 
`"payload_schema":{"doi":{"data_type":"keyword","points":71189953},"pid":{"data_type":"keyword","points":76775681}`

I am under the impression that there should be an additional field "indexed" set to True. Does this mean that somethign went wrong with my indexes?

Also I forgot to mention that the cluster is currently NOT busy at all. All ingestions have been completed and I see no optimizations running (green status on the collection)

**Comment by timvisee** [comment]
> Sorry if this is a rookie question but I was under the impression that I had successfully indexed two fields in my collection "pid" and "doi" but i realise that they may be wrong:
"payload_schema":{"doi":{"data_type":"keyword","points":71189953},"pid":{"data_type":"keyword","points":76775681}

No this seems about right - assuming these two fields always have 'keyword' values. All fields listed in `payload_schema` are indexed, and the point count confirms that.

Could you share an example of your delete request. That'll be helpful with debugging.

**Comment by StratosKakalis** [comment]
Admittedly, the field "pid" is numeric and should have the "Integer" type. I created the index with "Keyword" type by accident and figured it didn't hurt, but maybe I was wrong. 

As for the delete request, I perform it in python: 
```
qdrant_client.delete(
                collection_name=qdrant_collection,
                points_selector=Filter(
                    must=[
                        FieldCondition(
                            key="pid",
                            match=MatchAny(any=batch_pids)
                        )
                    ]
                )
            )

```
Where batch_pids is a list of 20 strings

**Comment by timvisee** [comment]
> Admittedly, the field "pid" is numeric and should have the "Integer" type. I created the index with "Keyword" type by accident and figured it didn't hurt, but maybe I was wrong.

The important thing is that your point data, and your operations use the same type.

Integers are much more efficient though, so I'd be a nice to have to change it.

In that case I'd recommend to:
- remove the `pid` index
- recreate the `pid` index as `integer`
- make sure that `batch_pids` are numbers (not strings) in your delete snippet

But it still isn't exactly clear to me why operations like this would take a long time.

Just to confirm, you're running a Qdrant server right? Not Qdrant local mode within the Python client.

**Comment by StratosKakalis** [comment]
Excuse me, the batch_pids type was actually int, could that be why it didn't work? Mismatch with the keyword type of the index? 

And yes I use Qdrant server, I launch the qdrant/qdrant image with docker

**Comment by timvisee** [comment]
> Excuse me, the batch_pids type was actually int, could that be why it didn't work? Mismatch with the keyword type of the index?

Definitely

**Comment by StratosKakalis** [comment]
Thank you SO MUCH! I took some time to verify that this fix worked and indeed everything is deleted instantly now. Thank you so much, I wouldn't have figured it out without you.

**Comment by timvisee** [comment]
Fantastic news! Happy to see it works now.
