### ISSUE TITLE
Discrepancy between indexed_vectors_count and points_count affecting query speed

### ISSUE THREAD

**Issue by dylanewbie** [qdrant/qdrant#4522]
Hi,

I'm encountering an issue where the indexed_vectors_count sometimes equals the points_count, and other times it is less than the points_count in my Qdrant Collection. This discrepancy seems to affect the query speed.
![image](https://github.com/qdrant/qdrant/assets/134046485/70cdac59-7d60-4793-bf04-8bbb77ca3a46)
![image](https://github.com/qdrant/qdrant/assets/134046485/92af01ad-eab0-4458-b060-4f10a3008c7e)

Could you please provide guidance on how to effectively increase the indexed_vectors_count so it matches the points_count to improve query performance? Additionally, is there a way to rebuild the index for a specific collection?

What factors might affect the number of indexed_vectors_count?

Thank you!

**Comment by timvisee** [comment]
First of all, please note that these numbers are approximate and may not be very reliable: https://qdrant.tech/documentation/concepts/collections/#approximate-point-and-vector-counts

It usually is normal if some points are not indexed. Internally, small chunks of points are not indexed because it only adds overhead. Once those chunks grow, they'll be indexed automatically.

To give a more direct answer, could you check/share the following:
- is there any CPU load on your machine, or does it look idle?
- could you share the collection information of the second collection, that is showing a big discrepancy in indexed vs count?

> What factors might affect the number of indexed_vectors_count?

Another thing to note is that the indexing threshold is configured in number of kilobytes. So the smaller your vectors are in terms of dimensionality, the more you'll need for the indexing threshold to be triggered. You can tweak this threshold for a collection or in the configuration file, but we usually recommend not doing this.

**Comment by dylanewbie** [comment]
@timvisee 
First of all, thank you for your response!

Here is some additional information for your reference:

- When inserting the second collection with 90,000 points, the machine was only performing this task (I will monitor the CPU usage for future inserts).

- Both the collections with 9 million points and 90,000 points were batch inserted using the same Python script.

- The second collection with 90,000 points was sampled from the 9 million points and saved as a CSV file before being inserted using the Python script (I'm not sure if this affects the data).

- I repeated the insertion of the 90,000 points collection (from the same CSV), and the `indexed_vectors_count ` varied each time. As shown in the attached image, it was 28,000 , sometimes 40,000 to 50,000, and even 0 at times.

- Please see the attached information for the second collection.
![image](https://github.com/qdrant/qdrant/assets/134046485/7c950d26-37d1-4fd8-8a23-e5dce31aad16)

**Comment by generall** [comment]
You can set `indexing_threshold` lower to force index creation

**Comment by dylanewbie** [comment]
> You can set `indexing_threshold` lower to force index creation

@generall 
Thank you for your response.
After setting the `indexing_threshold` to 1000, the issue was successfully resolved.

**Comment by kunalchamoli** [comment]
Qdrant in their [official documentation](https://qdrant.tech/documentation/guides/configuration/#configuration-options) mention
    indexing_threshold_kb: 20000

What different does it actually make to have a lower threshold of indexing ?
@dylanewbie @generall @timvisee

**Comment by timvisee** [comment]
There is no difference, `indexing_threshold` and `indexing_threshold_kb` are both recognized as the same.

> What difference does it actually make to have a lower threshold of indexing ?

Lowering the threshold means that your data will be indexed more aggressively. It'll potentially get you better indexed data, at the cost of a bit of performance degradation while indexing is going on in the background.

**Comment by kunalchamoli** [comment]
So i am guessing only the response time of search will get better, it should have no change in quality.

**Comment by timvisee** [comment]
The response time could get better, yes. Search quality may be slightly reduced, however, if it's a very small percentage of points the change in search quality is likely unnoticeable.

It's hard to conclude all of this just on the current facts. I'd recommend to give the change a shot and see if it meets your requirements.
