### ISSUE TITLE
When I delete the collection, Ram usage doesn't decrease

### ISSUE THREAD

**Issue by dingyao422** [qdrant/qdrant#5110]
Hi, I'm testing Qdrant Ram usage。My linux total memory is 8GB.
I created 1500+ collections, and all collection add some points, the Ram usage is 43%(use 'cat /proc/<qdrant-pid>/status | grep Rss' is 3,380,746 kB). Then I deleted all collections. The Ram usage doesn't decrease much, just from 43% to 38.7%(use 'cat /proc/<qdrant-pid>/status | grep Rss' is 3042672 kB).
In this moment, I also tested repeate create the collections and points, the Ram usage doesn't increase much, just coming back to about 43%. 
But I want the Qdrant Ram can auto vacuum, release to system. Because when Ram usage reaches a specified threhold, our monitoring system will issue an alarm. So Is there any way the Qdrant can free up memory for the system other than restart.

**Comment by timvisee** [comment]
Before we dive into memory usage I'd like to emphasize that we strongly recommend not creating that many collections.

Instead we highly recommend to put everything in a single collection, because it's much faster and more efficient. If you're using more than a few you're probably using Qdrant wrong. Please see our documentation on multitenancy here: https://qdrant.tech/documentation/guides/multiple-partitions/

**Comment by dingyao422** [comment]
Thanks for your answer. We may need to refer to this document to adjust our design.
