### ISSUE TITLE
A bug in GraphLayerBuilder when selecting candidates with heuristic

### ISSUE THREAD

**Issue by hicder** [qdrant/qdrant#5224]
I was reading this function, and in particular [this line](https://github.com/qdrant/qdrant/blob/9c20e9e27960228019b4606f137ca82b42fc3e66/lib/segment/src/index/hnsw_index/graph_layers_builder.rs#L275).

I think the condition should be reverse? In the paper, it says: 
```
The heuristic examines the candidates starting from the nearest (with respect to the inserted element) and creates a connection to a candidate only if it is closer to the base (inserted) element compared to any of the already connected candidates 
```

Also, in the hnswlib, it's also [reverse](https://github.com/nmslib/hnswlib/blob/c1b9b79af3d10c6ee7b5d0afa1ce851ae975254c/hnswlib/hnswalg.h#L470) and following the paper. So I think the qdrant implementation has a bug.

Apologies if I understand the code wrong.

**Comment by generall** [comment]
Hey @hicder! I think the confusion here caused by naming of `distance` vs `score`. While by distance we understand something which if lower means more similar, the similarity `score` is reversed - higher value means more similar. 
Qdrant internally assumes that all metric functions are similarity scores, like dot product or cosine similarity. Euclidean distance is inversed for this purpose internally, and later inversed back for displaying to the user

**Comment by hicder** [comment]
ah, that's what I'm missing. thank you for the explanation!
