### ISSUE TITLE
[sharding] Better pooling strategy for gRPC channels

### ISSUE THREAD

**Issue by agourlay** [qdrant/qdrant#589]
**Is your feature request related to a problem? Please describe.**
In order to improve the latency we have introduced pooling for gRPC channels in https://github.com/qdrant/qdrant/issues/518

This first approach uses a simple strategy which has the two following drawbacks.

1. uses of a fixed size pool which lacks flexibility and resilience under load
2. picks a random channel from the pool regardless of the current availability of the channels.

**Describe the solution you'd like**

Ideally we need a solution that:
1. resize automatically the pools according to the load
2. pick the least loaded channel from the pool

It is possible to reuse components from the [Tower](https://docs.rs/tower/latest/tower/index.html) library.

There are two different [balancing middlewares](https://docs.rs/tower/latest/tower/balance/index.html) that could be used.

- [p2c](https://docs.rs/tower/latest/tower/balance/p2c/index.html) which randomly picks two services from the set of ready endpoints and selects the least loaded of the two.
- [pool](https://docs.rs/tower/latest/tower/balance/pool/index.html) which implements a dynamically sized pool of services.

Both middlewares need a way to determine the load on the channels, this can be done by using the the `PendingRequest` default `Load` implementation.

e.g. of pseudo Rust code

```rust
let mut channels = Vec::with_capacity(self.pool_size);
 for _ in 0..self.pool_size {
    let channel = self.make_channel(uri.clone()).connect().await?;
    let tracked_channel = PendingRequests::new(channel, CompleteOnResponse::default());
    channels.push(tracked_channel);
 }

let service = Balance::new(tower::discover::ServiceList::new(channels));
```

**Comment by generall** [comment]
I am wondering what the `least loaded channel` is? I mean technically channels are only logical abstraction over the same physical networking hardware - by creating new channels we wont increase a bandwidth. On the other hand, it could be different CPUs assigned to listen and process requests for each channel individually - is that a case here?

**Comment by agourlay** [comment]
removed the `to be released` label as we will release the naive pooling but not the potential better version described here

**Comment by erare-humanum** [comment]
So, if I understand correctly, you create a `TransportChannelPool` that maps URI:s to `ChannelPools` containing a Vec of `Tonic::Transport::Channel` instantiated with the same URI' 

Wont multiple `Tonic::Transport::Channel`’s pointing to the same URI result in a single TCP connection (unless you need to reestablish the connection)?

From https://docs.rs/tonic/latest/tonic/transport/struct.Channel.html#multiplexing-requests I understand that in order to multiplex request you have to clone the channel (which is cheap), so is that not what you want to do instead?

Is it not load balancing between endpoints you want to achieve? That can be done via `tonic::channel::balance_list` or via the drop in replacement for tonic called ‘Ginepro’ (https://docs.rs/ginepro/latest/ginepro/index.html) that includes configurable, periodic, client side service discovery (via DNS) for gRPC servers and load balancing via p2c. I think Ginepro is made with `tower::Balance` just as  the pseudocode solution for this issue.

Forgive me if im wrong, I only started looking at this project today. Anyways I would be happy to help out if you want.

**Comment by generall** [comment]
The original intent and hypothesis was that creating multiple TCP connections to the same peer could improve throughput

**Comment by generall** [comment]
There is some reasoning why multiple RPC channels might be beneficial: https://grpc.io/docs/guides/performance/

> Each gRPC channel uses 0 or more HTTP/2 connections and each connection usually has a limit on the number of concurrent streams. When the number of active RPCs on the connection reaches this limit, additional RPCs are queued in the client and must wait for active RPCs to finish before they are sent. Applications with high load or long-lived streaming RPCs might see performance issues because of this queueing.
