### ISSUE TITLE
Replace BLAS with packed_simd

### ISSUE THREAD

**Issue by generall** [qdrant/qdrant#82]
https://github.com/rust-lang/packed_simd

**Is your feature request related to a problem? Please describe.**
`BLAS` is currently used for a single purpose - to make dot production faster. It looks like overkill. 
Compile time is pretty high and it complicates the development 

**Describe the solution you'd like**
Replace `BLAS` with `packed_simd` library, which appear to be much lighter.

**Describe alternatives you've considered**
Use some other lightweight library for SIMD (idk which one)

**Additional context**
None

**Comment by salamer** [comment]
[hora](https://github.com/hora-search/hora) have used `packed_simd` as its SIMD backend, but it can only be built in `nightly` version, and `packed_simd` has not iterated for a couple of months, and `packed_simd` looks like merge into stable version is still in the foreseeable future.  if you don't have installation pressure, `BLAS` may be a better choice, because it has proved itself in many projects.

**Comment by generall** [comment]
Hi @salamer! I was looking at hora when submitted this issue;) As a matter of fact, BLAS is a pain point when it comes to compilation. I also would like to avoid one unnecessary vector copy which is only used due to ndarray package. I would probably have to spend some more time on this topic and choose fast and at the same time easy to use package for SIMD.

**Comment by generall** [comment]
Different approach to consider https://github.com/zhao-lang/redis_hnsw/blob/master/src/hnsw/metrics.rs
